# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12-h8IItj_2PUIKN6gcg2olmwS_-H0snU
"""

import pandas as pd
import re


def data_cleaner():

    df = pd.read_csv('~/ip_files/raw_store_transactions.csv')


    def clean_store_location(st_loc):
        return re.sub(r'[^\w\s]', '', st_loc).strip()



    df['STORE_LOCATION'] = df['STORE_LOCATION'].map(lambda x: clean_store_location(x))



    def clean_product_id(pd_id):
        matches = re.findall(r'\d+', pd_id)
        if matches:
            return matches[0]
        return pd_id



    df['PRODUCT_ID'] = df['PRODUCT_ID'].map(lambda x : clean_product_id(x))



    def remove_dollar(amount):
        return float(str(amount).replace('$', ''))


    for to_clean in ['MRP', 'CP', 'DISCOUNT', 'SP']: df[to_clean] = df[to_clean].map(lambda x : remove_dollar(x))


    df.to_csv('~/op_files/fin.csv', index=False)